include php::restart
include mysql::start
include mysql::database
include mysql::password
include wordpress::wget
include wordpress::untar
include wordpress::move
include wordpress::config
include wordpress::restart
